// scripts/export-sqlite-to-supabase.ts
//
// One-off migration helper that copies the SQLite demo data (data.db) into a
// Supabase project under a specific tenant_id. Safe to run repeatedly;
// rows are upserted on the natural keys where possible.
//
// Usage:
//
//   # Print plan only (no writes)
//   npx tsx scripts/export-sqlite-to-supabase.ts \
//     --tenant-id <uuid> --db ./data.db --dry-run
//
//   # Run for real (requires env vars)
//   SUPABASE_URL=https://xxx.supabase.co \
//   SUPABASE_SERVICE_ROLE_KEY=sk_service_... \
//   npx tsx scripts/export-sqlite-to-supabase.ts --tenant-id <uuid>
//
// Flags:
//   --tenant-id    REQUIRED. The Supabase tenants.id to attach all rows to.
//   --db           Path to the SQLite file. Default ./data.db.
//   --dry-run      Print row counts and sample mappings, do not write.
//   --skip-events  Don't migrate widget_events (often the largest table).
//
// Tables migrated:
//   leads, integrations, widget_events
//
// Tables NOT migrated (low value or already migration-managed):
//   webhook_deliveries — high-volume log, regenerated by live traffic.

import Database from "better-sqlite3";
import { createClient } from "@supabase/supabase-js";
import { parseArgs } from "node:util";
import { existsSync } from "node:fs";

interface Args {
  tenantId: string;
  dbPath: string;
  dryRun: boolean;
  skipEvents: boolean;
}

function parseArgsOrExit(): Args {
  const { values } = parseArgs({
    options: {
      "tenant-id": { type: "string" },
      db: { type: "string", default: "./data.db" },
      "dry-run": { type: "boolean", default: false },
      "skip-events": { type: "boolean", default: false },
      help: { type: "boolean", default: false },
    },
    allowPositionals: false,
  });
  if (values.help) {
    console.log(
      "Usage: tsx scripts/export-sqlite-to-supabase.ts --tenant-id <uuid> [--db path] [--dry-run] [--skip-events]",
    );
    process.exit(0);
  }
  if (!values["tenant-id"]) {
    console.error("error: --tenant-id is required");
    process.exit(1);
  }
  return {
    tenantId: String(values["tenant-id"]),
    dbPath: String(values.db ?? "./data.db"),
    dryRun: Boolean(values["dry-run"]),
    skipEvents: Boolean(values["skip-events"]),
  };
}

function getSupabaseFromEnv() {
  const url = process.env.SUPABASE_URL;
  const key = process.env.SUPABASE_SERVICE_ROLE_KEY;
  if (!url || !key) {
    console.error(
      "error: SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY must be set (use --dry-run to test without writes)",
    );
    process.exit(1);
  }
  return createClient(url, key, {
    auth: { persistSession: false, autoRefreshToken: false },
  });
}

function safeJson<T>(s: string | null | undefined, fallback: T): T {
  if (!s) return fallback;
  try {
    return JSON.parse(s) as T;
  } catch {
    return fallback;
  }
}

interface SqliteLead {
  id: number;
  name: string;
  email: string;
  phone: string;
  address: string;
  language: string;
  trade: string;
  measurement: number;
  measurement_unit: string;
  material: string;
  addons_json: string;
  low_estimate: number;
  high_estimate: number;
  line_items_json: string;
  geometry_json: string;
  source_url: string;
  status: string;
  created_at: number;
}

interface SqliteIntegration {
  id: number;
  provider: string;
  display_name: string;
  category: string;
  enabled: number;
  endpoint: string;
  secret: string;
  auth_header: string;
  events_json: string;
  last_status: string;
  last_status_code: number | null;
  last_tested_at: number | null;
  last_delivered_at: number | null;
  created_at: number;
  updated_at: number;
}

interface SqliteWidgetEvent {
  id: number;
  session_id: string;
  event_type: string;
  trade: string;
  step: string;
  language: string;
  source_url: string;
  tenant: string;
  metadata_json: string;
  created_at: number;
}

async function main() {
  const args = parseArgsOrExit();

  if (!existsSync(args.dbPath)) {
    console.error(`error: SQLite database not found at ${args.dbPath}`);
    process.exit(1);
  }
  const sqlite = new Database(args.dbPath, { readonly: true });

  // Pull rows
  const leads = sqlite.prepare("select * from leads order by created_at asc").all() as SqliteLead[];
  const integrations = sqlite
    .prepare("select * from integrations order by id asc")
    .all() as SqliteIntegration[];
  const events = args.skipEvents
    ? []
    : (sqlite
        .prepare("select * from widget_events order by created_at asc")
        .all() as SqliteWidgetEvent[]);

  console.log(`[export] ${leads.length} leads, ${integrations.length} integrations, ${events.length} events`);
  console.log(`[export] tenant_id = ${args.tenantId}`);

  if (args.dryRun) {
    console.log("[export] --dry-run: showing first row of each table mapped to Supabase shape:");
    if (leads[0]) console.log("  leads[0]", JSON.stringify(mapLead(leads[0], args.tenantId), null, 2));
    if (integrations[0])
      console.log(
        "  integrations[0]",
        JSON.stringify(mapIntegration(integrations[0], args.tenantId), null, 2),
      );
    if (events[0])
      console.log("  events[0]", JSON.stringify(mapEvent(events[0], args.tenantId), null, 2));
    console.log("[export] dry-run complete — no writes performed.");
    return;
  }

  const supabase = getSupabaseFromEnv();

  // Confirm tenant exists before touching anything else.
  const { data: tenant, error: tErr } = await supabase
    .from("tenants")
    .select("id, name")
    .eq("id", args.tenantId)
    .single();
  if (tErr || !tenant) {
    console.error(`error: tenant ${args.tenantId} not found in Supabase: ${tErr?.message ?? "no row"}`);
    process.exit(1);
  }
  console.log(`[export] target tenant: ${tenant.name} (${tenant.id})`);

  // Leads — chunked insert
  await chunked(leads, 200, async (chunk) => {
    const payload = chunk.map((l) => mapLead(l, args.tenantId));
    const { error } = await supabase.from("leads").insert(payload);
    if (error) throw error;
  });
  console.log(`[export] inserted ${leads.length} leads`);

  // Integrations — upsert on (tenant_id, provider)
  if (integrations.length > 0) {
    const { error } = await supabase
      .from("integrations")
      .upsert(integrations.map((i) => mapIntegration(i, args.tenantId)), {
        onConflict: "tenant_id,provider",
      });
    if (error) throw error;
    console.log(`[export] upserted ${integrations.length} integrations`);
  }

  // Events
  if (events.length > 0) {
    await chunked(events, 500, async (chunk) => {
      const payload = chunk.map((e) => mapEvent(e, args.tenantId));
      const { error } = await supabase.from("widget_events").insert(payload);
      if (error) throw error;
    });
    console.log(`[export] inserted ${events.length} widget_events`);
  }

  console.log("[export] migration complete.");
}

async function chunked<T>(items: T[], size: number, fn: (chunk: T[]) => Promise<void>) {
  for (let i = 0; i < items.length; i += size) {
    await fn(items.slice(i, i + size));
  }
}

function mapLead(l: SqliteLead, tenantId: string) {
  return {
    tenant_id: tenantId,
    name: l.name,
    email: l.email,
    phone: l.phone,
    address: l.address,
    language: l.language,
    trade: l.trade,
    measurement: l.measurement,
    measurement_unit: l.measurement_unit,
    material: l.material,
    addons: safeJson(l.addons_json, []),
    low_estimate: l.low_estimate,
    high_estimate: l.high_estimate,
    line_items: safeJson(l.line_items_json, []),
    geometry: safeJson(l.geometry_json, null),
    source_url: l.source_url,
    status: l.status,
    created_at: new Date(l.created_at).toISOString(),
  };
}

function mapIntegration(i: SqliteIntegration, tenantId: string) {
  return {
    tenant_id: tenantId,
    provider: i.provider,
    display_name: i.display_name,
    category: i.category,
    enabled: Boolean(i.enabled),
    endpoint: i.endpoint,
    secret: i.secret,
    auth_header: i.auth_header,
    events: safeJson<string[]>(i.events_json, ["lead.created"]),
    last_delivery_status: i.last_status || null,
    last_delivery_code: i.last_status_code,
    last_tested_at: i.last_tested_at ? new Date(i.last_tested_at).toISOString() : null,
    last_delivery_at: i.last_delivered_at ? new Date(i.last_delivered_at).toISOString() : null,
    created_at: new Date(i.created_at).toISOString(),
    updated_at: new Date(i.updated_at).toISOString(),
  };
}

function mapEvent(e: SqliteWidgetEvent, tenantId: string) {
  return {
    tenant_id: tenantId,
    session_id: e.session_id,
    event_type: e.event_type,
    trade: e.trade,
    step: e.step,
    language: e.language,
    source_url: e.source_url,
    metadata: safeJson(e.metadata_json, {}),
    created_at: new Date(e.created_at).toISOString(),
  };
}

main().catch((err) => {
  console.error("[export] fatal:", err?.message ?? err);
  process.exit(1);
});
